apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  labels:
    kratix.io/promise-version: v0.0.1
  name: database
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: databases.demo.kratix.io
    spec:
      group: demo.kratix.io
      names:
        kind: Database
        plural: databases
        singular: database
      scope: Namespaced
      versions:
      - name: v1beta1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  size:
                    type: string
                type: object
            type: object
        served: true
        storage: true
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: null
      storedVersions: null
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: dependencies
        spec:
          containers:
          - image: kratix-demo/promise-pipeline:v0.1.0
            name: configure-deps
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: database-configure
        spec:
          containers:
          - image: kratix-demo/resource-pipeline:v0.1.0
            name: kratix-demo-resource-pipeline
status: {}
