apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: example-deployment
  labels:
    kratix.io/promise-version: v0.1.0
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: examples.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: Example
        plural: examples
        singular: example
      scope: Namespaced
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    key:
                      type: string
                  required:
                    - key
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - name: promise-configure
                image: ghcr.io/syntasso/example-deployment-configure:v0.0.1
                command: ["python", "configure.py", "promise-configure"]
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: resource-configure
          spec:
            containers:
              - name: resource-configure
                image: ghcr.io/syntasso/example-deployment-configure:v0.0.1
                command: ["python", "configure.py", "resource-configure"]