apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: config
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: configs.syntasso.io
    spec:
      group: syntasso.io
      names:
        kind: config
        plural: configs
        singular: config
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  fields:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise: 
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-python/sdk-test:v1.0.0
            name: promise-pipeline
            command: ["python", "configure.py", "promise-configure"]
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-python/sdk-test:v1.0.0
            name: resource-pipeline
            command: ["python", "configure.py", "resource-configure"]